### ISSUE TITLE
20-files-present-and-referenced fails on %{python_subpackages} in python-wheel

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/obs-service-source_validator#50]
Report from `factory-auto` in https://build.opensuse.org/request/show/512806. After some debugging I boiled it down to removing that line locally as it remains posts all the replacements and is then complained about.

The temp file passed to `$RPMBUILD` which complained about line 21.

```
     1  #
     2  #
     3  #
     4
     5  #
     6
     7
     8  %{?!python_module:%define python_module() python-%{**} python3-%{**}}
     9  %{!?license: %global license %doc}
    10  Name:           python-wheel
    11  Version:        0.29.0
    12  Release:        0
    13  Summary:        A built-package format for Python
    14  License:        MIT
    15  Group:          Development/Languages/Python
    16  Url:            http://bitbucket.org/pypa/wheel/
    17  ##seen Source:         https://files.pythonhosted.org/packages/source/w/wheel/wheel-%{version}.tar.gz
    18  %{echo:https://files.pythonhosted.org/packages/source/w/wheel/wheel-%{version}.tar.gz }
    19  BuildArch: x86_64
    20
    21  %{python_subpackages}
    22
    23
    24  %description
```

**Comment by jberry-suse** [comment]
Interestingly this does not error when run via `osc service localrun source_validator`, but does when run as part of `factory-auto` bot:
- https://github.com/openSUSE/osc-plugin-factory/blob/master/check_source.py#L85
- https://github.com/openSUSE/osc-plugin-factory/blob/master/source-checker.pl

Which issues:
`/bin/bash /usr/lib/obs/service/source_validators/20-files-present-and-referenced --batchmode ~/co/512806/python-wheel ~/co/512806/_old < /dev/null 2>&1`

**Comment by jberry-suse** [comment]
Original report from https://lists.opensuse.org/opensuse-packaging/2017-08/msg00000.html.

**Comment by matejcik** [comment]
relevant part here is what line 21 _does_: It executes a fairly complex Lua macro, which tries to locate file `%{name}.spec` in the current directory, `%{_sourcedir}` or `%{_specdir}`. It fails with "bad spec" when the file is not found or can't be opened.

see https://github.com/openSUSE/python-rpm-macros/blob/master/macros.lua#L56 and https://github.com/openSUSE/python-rpm-macros/blob/master/macros.lua#L302

So my assumption is that the spec file is either a) not called `%name.spec`, or b) not present in any of the listed directories. I can also fix the problem on my side, by modifying the macro to look for it in the right place.

It could also be some sort of IO error on opening, but that seems unlikely, as the process opening it is the same one that is reading the spec file in the first place. Maybe if the spec was unlinked after opening it?

In practice, the same macro with the same code works fine on majority of packages, but sometimes inexplicably fails. From a quick look, it seems that `~/co/512806/python-wheel` is not `%{_sourcedir}` nor `%{_specdir}`, so it's looking in the current directory. Is it possible that sometimes the script is running from the same directory as the spec and sometimes not?

**Comment by jberry-suse** [comment]
I do not see how it would not run from the same directory relative the the spec each time. See: https://github.com/openSUSE/osc-plugin-factory/blob/master/source-checker.pl#L109

Changing that line to:
```
my $checkivsd = `cd $dir && /bin/bash $test --batchmode $dir $old < /dev/null 2>&1`;
```

Seems to make everything happy so your suggestion about the directory seems correct. From the perspective of validator I assume that is what it expects given that `osc service localrun source_validator` does not fail I would imagine that is due to invoking from the same directory as spec.

**Comment by jberry-suse** [comment]
Personally, I would not expect this to be a requirement given that validator accepts directory arguments. Seems like either the macro or validator should be tweaked to handle this.

**Comment by matejcik** [comment]
I may have figured out a more reliable way to locate the spec file.

(Turns out there is a macro `%_specfile` that contains the location. It would be so amazing if things like this were documented somewhere.)

If this survives my rebuild tests, this bug will go away without modifying the source validator.

**Comment by scarabeusiv** [comment]
This is now fixed in master as we merged PR #39 
As we are no longer using the rpmbuild to parse it but just grab the content we need we are no-longer triggering issues with partially parsed files.

**Comment by sebix** [comment]
is this also fixed in the build service?

**Comment by jberry-suse** [comment]
The machine on which the bot runs is using `obs-service-source_validator` version `0.6+git20170811.369eb25-106.1` which was updated 4 days ago (after this was committed).

**Comment by sebix** [comment]
I still see these errors:
https://build.opensuse.org/request/show/517246
https://build.opensuse.org/request/show/517243
https://build.opensuse.org/request/show/513738

**Comment by jberry-suse** [comment]
Unfortunately https://bugzilla.opensuse.org/show_bug.cgi?id=1053969 occured and resulted in the package be rolled back.
